import { fontTitle, gradient } from '@ziro/theme';

export const container = {
    display: 'grid',
    padding: '10px',
    gridRowGap: '20px',
    alignContent: 'start',
  },
  button = {
    margin: '10px auto 0',
    display: 'block', // necessary for link version
    WebkitAppearance: 'none',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    MozAppearance: 'none',
    outline: 'none',
    cursor: 'pointer',
    height: '30px',
    width: '100%',
    maxWidth: '200px',
    padding: '8px 0px',
    border: 'none',
    borderRadius: '20px',
    fontFamily: fontTitle,
    fontSize: '1.3rem',
    color: '#FFF',
    textAlign: 'center',
    background: gradient,
    boxShadow: `0px 3px 12px -3px rgba(34,34,34,0.65)`,
  },
  card = {
    display: 'grid',
    padding: '20px 10px',
    background: 'white',
    gridGap: '10px',
    borderRadius: '3px',
    boxShadow: 'rgba(34, 34, 34, 0.3) 0px 5px 10px -1px',
  },
  cardHeader = {
    display: 'grid',
    gridTemplateColumns: 'auto auto',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '5px',
  },
  brandName = {
    fontFamily: fontTitle,
  },
  trashButton = {
    height: 21,
    width: 21,
    display: 'grid',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContent = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gridGap: '10px',
  },
  thumb = image => ({
    position: 'relative',
    background: `url('${image}') center / cover`,
    width: (Math.min(400, window.innerWidth) - 60) / 3,
    height: (Math.min(400, window.innerWidth) - 60) / 3,
  }),
  excludeButton = {
    position: 'absolute',
    top: 5,
    right: 5,
    height: 25,
    width: 25,
    borderRadius: '50%',
    background: 'rgba(150,150,150,0.95)',
    display: 'grid',
    justifyContent: 'center',
    alignItems: 'center',
  };
